
server:
  port: 8081
  servlet:
    context-path: /identity
  error:
    include-message: always
    include-binding-errors: always

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/identity_services
    username: Dbaohz
    password: leducbao011020
  mail:
      host: localhost
      port: 1025
      username: bao
      password: 123321
      properties:
        mail:
          smtp:
            ssl:
              trust: "*"
            auth: true
            transport:
              protocol: smtp
            starttls:
              enable: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000
